=== Necoro/portato/plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://portato.sourceforge.net/plugin" targetNamespace="http://portato.sourceforge.net/plugin" elementFormDefault="qualified">
	<xs:element name="plugin">
		<xs:complexType>
			<xs:all>
				<xs:element name="name" type="string" />
				<xs:element name="author" type="string" />
				<xs:element name="import" type="importString" minOccurs="0"/>
				<xs:element name="frontends" type="stringList" minOccurs="0" />
				<xs:element name="hooks" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="hook" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="connect" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="type" default="before">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="before" />
																	<xs:enumeration value="override" />
																	<xs:enumeration value="after" />
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="type" type="string" use="required" />
									<xs:attribute name="call" type="functionCall" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="options" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="option" minOccurs="1" maxOccurs="unbounded" type="string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="menu" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="string">
											<xs:attribute name="call" type="functionCall" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="importString">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z_]+\.?)+" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="functionCall">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z_][0-9a-zA-Z_]*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="string">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="_stringList">
		<xs:list itemType="string"/>
	</xs:simpleType>
	<xs:simpleType name="stringList">
		<xs:restriction base="_stringList">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Necoro/portato/plugins/new_version.xml
<?xml version="1.0" encoding="UTF-8" ?>
<plugin xmlns="http://portato.sourceforge.net/plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://portato.sourceforge.net/plugin http://portato.sourceforge.net/plugin.xsd">

	<author>Ren√© 'Necoro' Neumann</author>
	<name>New Version Reminder</name>

	<import>portato.plugins.new_version</import>

	<hooks>
		<hook type="after_startup" call="find_version" />
	</hooks>

	<menu>
		<item call="find_version">Check for new _versions</item>
	</menu>

	<options>
		<option>disabled</option>
	</options>


</plugin>

=== Necoro/portato/plugins/etc_proposals.xml
<?xml version="1.0" encoding="UTF-8" ?>
<plugin xmlns="http://portato.sourceforge.net/plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://portato.sourceforge.net/plugin http://portato.sourceforge.net/plugin.xsd">

	<author>René 'Necoro' Neumann</author>
	<name>Etc-proposals plugin</name>

	<import>portato.plugins.etc_proposals</import>

	<hooks>
		<hook type = "after_emerge"	call = "etc_prop">
			<connect type="after" />
		</hook>
	</hooks>

	<menu>
		<item call="etc_prop_menu">Et_c-Proposals</item>
	</menu>

</plugin>

=== Necoro/portato/plugins/old/shutdown.xml
<?xml version="1.0" encoding="UTF-8" ?>
<plugin xmlns="http://portato.sourceforge.net/plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://portato.sourceforge.net/plugin http://portato.sourceforge.net/plugin.xsd">
	<author>René 'Necoro' Neumann</author>
	<name>Shutdown</name>
	<import>portato.plugins.shutdown</import>

	<hooks>
		<hook type = "after_emerge"	call = "shutdown">
			<connect type="after">*</connect>
		</hook>
	</hooks>

	<options>
		<option>disabled</option>
	</options>
</plugin>
